### ISSUE TITLE
.NET 5.0

### ISSUE THREAD

**Issue by IceReaper** [theolivenbaum/h5#25]
I know, a bit early, but what are the plans on .NET 5.0?

**Comment by IceReaper** [comment]
One of the problems i found so far is, that when having net5.0 installed (ubuntu 20.04, using rider as IDE),
the compilation fails with
```Sdk.targets(201, 9): [NETSDK1005] Assets file 'obj/project.assets.json' doesn't have a target for '.NETStandard,Version=v2.0'. Ensure that restore has run and that you have included '.NETStandard,Version=v2.0' in the TargetFrameworks for your project.```
while using
```<TargetFramework>netstandard2.0</TargetFramework>```.
However when using
```<TargetFramework>.NETStandard,Version=v2.0</TargetFramework>```
the error is gone. The compilation itself then crashes with the message
```H5 : error H5003: The SDK 'h5.Target/0.0.11500' specified could not be found.```

**Comment by theolivenbaum** [comment]
Hi @IceReaper - I think I hit that before, seems like something strange changed on the MSBuild included in the NET5.0.
What's happening is that MSBuild is not locating the nuget package that contains the project SDK target (https://www.nuget.org/packages/h5.target/) and is not restoring it either.
I'm planning to start updating our own stack to net50 quite soon, and that will start with h5. I'll post an update here as soon as I've some time to get this going!

**Comment by theolivenbaum** [comment]
by the way - fully uninstalling the net50 preview and keeping only the netcore3.1 sdk fixed the issue for me - you might want to give it a try!

**Comment by IceReaper** [comment]
Nope, i've created another issue for now for net 3.1, so the two versions do not mix up here.

**Comment by theolivenbaum** [comment]
@IceReaper finally updated to net5.0 - think I found the cause of the bug when using the latest MSBuild (https://github.com/dotnet/msbuild/issues/5875), and a workaround for it. Will be available soon!

**Comment by theolivenbaum** [comment]
@IceReaper published the updated compiler, targets, etc... now supporting NET5.0 :)

https://www.nuget.org/packages/h5-compiler
https://www.nuget.org/packages/h5.target

Let me know if you hit any issues post-update!

**Comment by IceReaper** [comment]
> @IceReaper finally updated to net5.0 - think I found the cause of the bug when using the latest MSBuild ([dotnet/msbuild#5875](https://github.com/dotnet/msbuild/issues/5875)), and a workaround for it. Will be available soon!

Building triggers precisely the problem you mentioned above. I tried to add the 4 workaround tags to my csproj file, but that didnt fix it.

**Comment by theolivenbaum** [comment]
Did you update the SDK target and the compiler?

**Comment by IceReaper** [comment]
<Project Sdk="h5.Target/0.0.13615"> and i did "dotnet tool update --global h5-compiler --version 0.0.1362"

Speaking of the dotnet tool update: Will this step always be required? If not, can you hint me when this is no longer required? I try to avoid to keep running such commands on our companys buildnodes which keep resetting after a build has been done.

**Comment by IceReaper** [comment]
Did some more tests: It is related to #29 Without any dependency it compiles correctly. Adding another library breaks it. So i guess #25 is resolved.
