### ISSUE TITLE
WebGL2RenderingContext

### ISSUE THREAD

**Issue by IceReaper** [theolivenbaum/h5#26]
Hello, as retyped isnt available, any plans on supporting WebGL2RenderingContext?

**Comment by theolivenbaum** [comment]
Is that available on an existing retyped package?

**Comment by IceReaper** [comment]
Yup https://www.nuget.org/packages/Retyped.webgl2/

**Comment by theolivenbaum** [comment]
Then I might be able to push an h5 package for it. Will check and let you
know!

**Comment by theolivenbaum** [comment]
@IceReaper Is there any other retyped package you would be interested at?

**Comment by IceReaper** [comment]
Atm not. Im working on a simple cross-platform app (desktop and web) which uses a wrapper for opentk / webgl2. The webgl2 package is the only missing component at the moment. If something else (non library, but base html5 api) comes up, ill make another issue about that.

**Comment by theolivenbaum** [comment]
Added the code here: https://github.com/theolivenbaum/h5/commit/39279355d2fe48b0ef4032f8e1cef2c67e33b5eb

Package is building, and if I didnt do any silly mistake, should be on nuget in 30 min on this link: https://nuget.org/packages/h5.webgl2

**Comment by theolivenbaum** [comment]
@IceReaper let me know if you hit any issues testing it - and also if any method from the current webgl api is missing since the original Retyped webgl release, those are usually easy to add on top of the code...

**Comment by IceReaper** [comment]
I can confirm this library works as expected under current H5 and .NET5
