### ISSUE TITLE
Support for the advanced text metrics api.

### ISSUE THREAD

**Issue by IceReaper** [theolivenbaum/h5#34]
Basically for our renderer, we need support for this api:
https://developer.mozilla.org/en-US/docs/Web/API/TextMetrics
Sadly, using measureText, H5 only knows about the "width" property.

**Comment by theolivenbaum** [comment]
just pushed the missing properties - should be in the next nuget package in a few minutes.
If you find anything else missing just open a new issue, these are usually easy to fix :)
