### ISSUE TITLE
Add console timing functions for benchmarking.

### ISSUE THREAD

**Issue by IceReaper** [theolivenbaum/h5#36]
https://developer.mozilla.org/en-US/docs/Web/API/Console/time
Would be nice to have the three time related functions available :)

**Comment by theolivenbaum** [comment]
Hi @IceReaper - you can already access them in the dom console (which is not the same as the System.Console class)

`````csharp
using static H5.Core.dom;

// ....

console.time("Time this");

for (var i = 0; i < 10000; i++) {
  // Your stuff here
}

console.timeEnd("Time this");
`````
