### ISSUE TITLE
Locales not supported

### ISSUE THREAD

**Issue by TriEdgeAI** [theolivenbaum/h5#44]
![image](https://user-images.githubusercontent.com/12459664/115637207-45c4cc80-a318-11eb-9383-4422dc6dbd11.png)

My h5.json:

```json
{
	"output": "../Shoptico.Core.Backend/wwwroot/$(AssemblyName)/",
	"sourceMap":
	{
		"enabled": false
	},
	"reflection":
	{
		"disabled": false
	},
	"locales": "en-US;en-GB;bg-BG", //if I keep this - I get the crash, if I remove it - it's okay
	"generateTypeScript": false,
	"cleanOutputFolderBeforeBuild": true,
	"logging":
	{
		"level": "None"
	},
	"loader":
	{
		"type": "ES6",
		"manualLoading": true,
		"skipManualVariables": true
	},
	"htmlx":
	{
		"keepJSDependencies": true
	}
}
```

**Comment by theolivenbaum** [comment]
Hi @TriEdgeAI - what does locales do on Bridge? I've never used it and I think I had removed it when doing the fork. Happy to add it back if useful

**Comment by TriEdgeAI** [comment]
It allows you to use `CultureInfo` essentially with locales other than `InvariantCulture`.

**Comment by TriEdgeAI** [comment]
Just checked, seems to be working, will report whether I managed to build our entire codebase a bit later.
