### ISSUE TITLE
Auto close compilation server.

### ISSUE THREAD

**Issue by IceReaper** [theolivenbaum/h5#47]
When using h5 projects in GitLab CI builds, the build will wait forever for the H5 compiler to close. There should be a way to ensure the compilation server shuts down either after a successful compilation, or after a specific idle time.

**Comment by theolivenbaum** [comment]
Hi @IceReaper!

 Good point, I forgot to add this to the readme - but you can use [this flag](https://github.com/theolivenbaum/h5/blob/f66b274b005fe961bb80e653794180ed4090a6c2/H5/Compiler/Compiler/Program.cs#L477) on the compilation:

`--no-server`

We already try to be smart to [detect CIs](https://github.com/theolivenbaum/h5/blob/f66b274b005fe961bb80e653794180ed4090a6c2/H5/Compiler/Compiler/Program.cs#L571) to avoid the compilation server, if you know any environment variable that is always defined on GitLab CI we can add it there too to avoid even needing the flag
