### ISSUE TITLE
h5 cdn files?

### ISSUE THREAD

**Issue by Ali1Jamal** [theolivenbaum/h5#50]
I hope cdn files for h5 will be provided this is well improve network download size alot.

**Comment by theolivenbaum** [comment]
Hi @Ali1Jamal,

There is now an option on the h5.json file under the html settings to use the CDN instead of the local h5.js:

`````json
{
    ...
    "html": {
        ...
        "useCDN" : true,
    }
}
`````

The files are also hosted here: https://cdn.jsdelivr.net/npm/@h5.rocks/h5@latest/dist/

**Comment by Ali1Jamal** [comment]
@theolivenbaum thank you for fast replay:
you are doing good job but the size of h5.min.js is (195 kb) because the Content-Encoding type is gzip algorithm not Brotli algorithm ..this is mean The size is a little bigger You can reduce the size to approximately 150kb if you use Brotli ....take a look at this website [https://cdnjs.com/](https://cdnjs.com/) the bridge.net use it because its use Brotli algorithm

**Comment by theolivenbaum** [comment]
I'll check it out, thought it would be negotiated automatically between the
browser and the CDN...
