### ISSUE TITLE
h5 now runs on NET6.0

### ISSUE THREAD

**Issue by theolivenbaum** [theolivenbaum/h5#52]
Since .net60 moved into the [go-live release](https://devblogs.microsoft.com/dotnet/announcing-net-6-release-candidate-1/) phase, I've updated h5 compiler to run on net6.0 to make sure it's ready. I've not hit any issues on my side, but I'm opening this issue to track any problems.

If you're updating the h5 compiler on your computer, you might need to install the net6.0 SDK first:
https://dotnet.microsoft.com/download/dotnet/6.0

Otherwise you can keep using the [last net5.0 version](https://www.nuget.org/packages/h5-compiler/0.0.21310) -  there were no new features on the [net6.0 version](https://www.nuget.org/packages/h5-compiler/0.0.21597).

**Comment by theolivenbaum** [comment]
Hi @eppoeh, thanks for reporting the issue - I'll push a fix asap!

**Comment by eppoeh** [comment]
Unfortunately not. Ended up reinstalling all all just works now. 

(biggest culprit was net6.0 not registering corrent in env tables, had to put the new path up in the list, mb still was using .net5 on the background?)

But tested again with a old config, still including locales. Just builds. I'm so happy now!

**Comment by theolivenbaum** [comment]
Hi @eppoeh, yeah that seems to be a known issue with the VS2022 installer - same thing happened to me. In the end was just a matter of fixing the path environment order. Thanks for the feedback :)
