### ISSUE TITLE
no an issue but a question. Anyway to debug (f9) step by step with chrome or firefox ?

### ISSUE THREAD

**Issue by ttournel** [theolivenbaum/h5#63]
Hi!

How to debug (f9) step by step with chrome or firefox ?

Thanks in advance,
Thierry

**Comment by hardhub** [comment]
The same as with Bridge? You need source map... I guess.

But if you have a real problem it is much better to debug generated JS or Console.WriteLine and check the output.

**Comment by theolivenbaum** [comment]
Agreed - I also disable the source-code mapping as I prefer to debug the generated JS.
Otherwise, yes you can debug using the browser developer tools.
