### ISSUE TITLE
h5.Target tries to install latest version instead specified

### ISSUE THREAD

**Issue by hardhub** [theolivenbaum/h5#64]
I get the following when use `<Project Sdk="h5.Target/0.0.21664">`:

```
Package h5-compiler 0.0.34002 is not compatible with net6.0 (.NETCoreApp,Version=v6.0) / any. Package h5-compiler 0.0.34002 supports: net7.0 (.NETCoreApp,Version=v7.0) / any
```

It is latest version compatible with .NET 6, but it still tries to install "0.0.34002" which requires .NET 7.

**Comment by hardhub** [comment]
Manual installing helps to workaround:

```
dotnet tool install --global h5-compiler --version 0.0.25007
```

**Comment by theolivenbaum** [comment]
You can also download the latest SDK, as I mentioned in #70

**Comment by hardhub** [comment]
The original idea was to avoid downloading NET 7 based SDK.  
Version which is compatible with .NET 6, should not try to download NET 7 based if NET 7 is not installed.  
It is just creates warning garbage in logs during compilation.
