### ISSUE TITLE
Extremely high RAM consumption in solution with multiple H5 projects.

### ISSUE THREAD

**Issue by hardhub** [theolivenbaum/h5#73]
If H5 needs to build a lot of projects for some reason it opens a lot of console windows, which all are closed except one.

That single process will do all work, but on opening H5 windows system eats a lot of RAM (**40GB**):

![image](https://user-images.githubusercontent.com/4306334/203998550-6bc56218-68ea-475d-855f-a189d7cfc8cd.png)

When the building continues it reduced as approximately to 20 GB. It is bigger than it was with Bridge maybe for 30%, but it is acceptable.   
Though 40 GB peaks are not good of course. It means that common PC with 32 GB cannot be used for comfort work on middle and big projects.

![image](https://user-images.githubusercontent.com/4306334/203999158-dd8e525e-9148-400d-bb38-6b2395a80d5f.png)

Mentioned solution has nine H5 projects inside. Some of them are really small. But it does not impact consumption, only projects count.

**Comment by hardhub** [comment]
Unfortunately building time is also dramatically increased in comparison with Bridge -  30 seconds vs 2 minutes

**Comment by hardhub** [comment]
It eats around 2 GB for H5 sever during building on **Linux**:

![image](https://user-images.githubusercontent.com/4306334/204087690-0bf5c363-1b17-4470-b818-5697b60c4665.png)

And after all that I tested **Windows 11**:

![image](https://user-images.githubusercontent.com/4306334/204087783-55db3983-7ad1-43b2-857a-57ebc9099553.png)

It looks like it does some memory leaks in Paded and Not Paged Pools. But I do not have any glue what is the reason yet.

Though I can say once again that targeting net7.0 and skipping support of NET 6 which is LTS release was a bad idea.

**Comment by hardhub** [comment]
As workaround it is possible to set environment variable `DOTNET_EnableWriteXorExecute=0` to solve the issue.

**Comment by theolivenbaum** [comment]
Interesting, seems to be related to https://github.com/dotnet/runtime/issues/79469
