### ISSUE TITLE
This page is not available

### ISSUE THREAD

**Issue by nsgnkhibdk2cls0f** [theolivenbaum/h5#76]
https://github.com/h5dotnet/Bridge/wiki/global-configuration

Referenced on https://github.com/theolivenbaum/h5/blob/master/Tests/Placeholder/h5.json

**Comment by hardhub** [comment]
Try to use web archive. I think H5 does not have copied documentation.

https://web.archive.org/web/20200929021729/https://github.com/bridgedotnet/Bridge/wiki/global-configuration

**Comment by nsgnkhibdk2cls0f** [comment]
Will it be fixed in the future?

**Comment by hardhub** [comment]
Ask @theolivenbaum, maybe he can some glue regarding that. But web-archive is what I am personally using for moment.

**Comment by theolivenbaum** [comment]
Unfortunatelly the bridge team deleted their wiki content, but well found to check archive.org @hardhub!
I've updated it now to point to the right place.
