### ISSUE TITLE
[Help] How to use with MonoGame?

### ISSUE THREAD

**Issue by RedstoneWizard08** [theolivenbaum/h5#77]
I'm trying to develop a game for the web with MonoGame and h5. How would I go about doing this? I can't find any documentation.

**Comment by theolivenbaum** [comment]
Hi @RedstoneWizard08, there seems to be a port to the original Bridge here:
https://github.com/harry-cpp/MonoGame/tree/bridge
It might be possible to update it to use h5 instead - but I've no experience with it
