### ISSUE TITLE
How do I access Bridge.Html5.Document.GetElementById?

### ISSUE THREAD

**Issue by Riccsson** [theolivenbaum/h5#78]
canvas = Bridge.Html5.Document.GetElementById<Bridge.Html5.HTMLCanvasElement>(canvasId);

How do I use this line of code in H5?

**Comment by Riccsson** [comment]
Sorry, i found it:
canvas = H5.Core.dom.document.getElementById<H5.Core.dom.HTMLCanvasElement>(canvasId);

**Comment by theolivenbaum** [comment]
No worries! Usually I add to the usings list this import, so you can use it directly without having to prefix with the whole namespace:

```````csharp
using static H5.Core.dom;
//...
var canvas = document.getElementById<HTMLCanvasElement>(canvasId);
```````

**Comment by hardhub** [comment]
> canvas = Bridge.Html5.Document.GetElementById<Bridge.Html5.HTMLCanvasElement>(canvasId);
> 
> How do I use this line of code in H5?

@Riccsson 
`C#
` HTMLCanvasElement element = Document.GetElementById<HTMLCanvasElement>("id");

You need to add h5 nuget package and namespace `H5.Html5;` to project and it will work;

**Comment by Riccsson** [comment]
I didnt find namespace H5.Html5. So I use H5.Core.dom instead.
The .As<T>() was a good thing 👍
Thank you

**Comment by hardhub** [comment]
> I didnt find namespace H5.Html5. So I use H5.Core.dom instead. The .As() was a good thing +1 Thank you

@Riccsson 

You are right, I forgot that I ported it from Bridge.Frameworks to separate library. So it is available for me as usual.

P.S. I use own fork of H5 built with .NET 6 instead of .NET 7 as well.
