### ISSUE TITLE
H5 does not respect CamelCasePropertyNamesContractResolver

### ISSUE THREAD

**Issue by hardhub** [theolivenbaum/h5#81]
Bridge applies camelcase but not H5.

I do not know the reason yet. So just created it here to track the problem.

**Comment by hardhub** [comment]
It looks like here it does not use camelCase variable to set `key`.

```JS
if (nometa) {
    if (obj.toJSON) {
        raw = obj.toJSON();
    } else {
        for (var key in obj) {
            if (obj.hasOwnProperty(key)) {
                raw[key] = Newtonsoft.Json.JsonConvert.SerializeObject(obj[key], formatting, settings, true);
            }
        }
    }
}
```

Using `raw[key.charAt(0).toLowerCase() + key.substr(1)]` for tests generates JSON with camelCase property name.

Strange thing that it works in Bridge. I have tested it and it says: nometa - false.

So in H5 - nometa is true, in Bridge is is false. Obviously above source code does not validate camelCase. So it has bug.

But it is not clear anything yet about `H5.getMetadata(type)`.

**Comment by hardhub** [comment]
> In H5 `t.$getMetadata` is undefined because it is Object, but in Bridge it is "$$fullname": "$AnonymousType$4".

I think this one is related to default behaviour set to [Rules(AnonymousType = AnonymousTypeRule.Plain)] which is not so in Bridge.

**Comment by theolivenbaum** [comment]
@hardhub changing the rule to the Bridge default fixed the issue for you?

**Comment by hardhub** [comment]
> @hardhub changing the rule to the Bridge default fixed the issue for you?

It is workaround to emulate Bridge behaviour. But in general it should have the fix:

![image](https://github.com/theolivenbaum/h5/assets/4306334/33d829ff-c322-45c8-a909-424f9a20db2b)

I have attached full version from my fork: [JsonConvert.zip](https://github.com/theolivenbaum/h5/files/11984710/JsonConvert.zip)

**Comment by theolivenbaum** [comment]
Thanks @hardhub, merged the change back to the json package now.
