### ISSUE TITLE
Consider migration to Gitlab?

### ISSUE THREAD

**Issue by ghost** [theolivenbaum/h5#87]
Microsoft playing stupid games already many years. Many good software was affected and now time of github ))

_GitHub users are [now required](https://github.blog/2023-03-09-raising-the-bar-for-software-security-github-2fa-begins-march-13/) to enable two-factor authentication as an additional security measure. Your activity on GitHub includes you in this requirement. You will need to enable two-factor authentication on your account before September 28, 2023, or be restricted from account actions_.

Can you consider migration to gitlab.com?

P.S. I used gitlab on-premise many years and it works really not bad, not worse than github even in community edition.

P.P.S. I think I will have to stop using github account. MS will not allow to login me without 2FA. So I will not be able to make any contribution, even comment issues )))

**Comment by theolivenbaum** [comment]
What's the issue with 2fFA? I've the app 2FA for as far as I remember and never had any issues... Are you being forced to use a mobile number?

**Comment by hardhub** [comment]
https://github.com/orgs/community/discussions/63813

**Comment by hardhub** [comment]
![image](https://github.com/theolivenbaum/h5/assets/4306334/4b6c0ad6-0f88-4778-bd76-5f5205f08702)

It was extremely easy and fast!
