### ISSUE TITLE
Conversion from es5.Promise<TResult> to Task<TResult> with ToTask() returns an Array object instead of TResult

### ISSUE THREAD

**Issue by YImhof** [theolivenbaum/h5#88]
In case of conversion from `Promise` to `Task` returning a result, the `getAwaitedResult` method returns the result encapsulated in an array.

For example, the following code never logs the resulting `Response` object, as `response.status` is `undefined`.
```
internal class Program
{
    static async Task Main(string[] args)
    {
        RequestInit request = new RequestInit()
        {
            keepalive = true
        };
        Response response = await fetch($"{window.location.href}any/call", request).ToTask();
        if (response.status == 404)
            console.log(response);
    }
}
```
Part of the transpiled code to JS:  
```
switch ($s) {
    case 0: {
        request = { keepalive: true };
        $t1 = System.Threading.Tasks.Task.fromPromise(fetch(System.String.format("{0}any/call", [window.location.href]), request));
        $s = 1;
        if ($t1.isCompleted()) {
            continue;
        }
        $t1.continue($asyncBody);
        return;
    }
    case 1: {
        $tr1 = $t1.getAwaitedResult();
        response = $tr1;
        if (response.status === 404) {
            console.log(response);
        }
    }
}
```
Variable `$tr1` is an array of length 1 having the `Response` object at index 0.
So perhaps, the line `response = $tr1;` should be `response = $tr1[0];` ?

For a complete information, you have to know that i am trying to create a h5 proxy for an existing TS class that returns promises, doing something similar to the above code, like the following:
```
[External]
[Name("idProvider")]
internal static class IdProvider
{
    [Template("System.Threading.Tasks.Task.fromPromise({this}.isLoginRedirect())")]
    public static extern Task<bool> IsLoginRedirect();
}
```
Calling `IsLoginRedirect` makes a call to the server getting an OIdC configuration to be applied, and so is asynchrone.
In both cases, `getAwaitedResult` returns the unexpected array object.

**Comment by YImhof** [comment]
Hello @theolivenbaum,

Thanks a lot for the feed-back and the solution. I tried it and the problem is solved.

Sorry that I missed the point of the input arguments pass-through.

**Comment by theolivenbaum** [comment]
No worries, I was also not aware of it 😅
