### ISSUE TITLE
[Feature-Request] Get rid of Mono.Cecil in favour of Roslyn

### ISSUE THREAD

**Issue by TriEdgeAI** [theolivenbaum/h5#9]
Which would in turn get rid of the need for `Preconvert()` and boost performance somewhat.

**Comment by theolivenbaum** [comment]
Problem is the Rewriter is needed for converting the C# code into the subset of the C# language that is supported by the transpiler. But with https://github.com/theolivenbaum/h5/blob/9163e7dab492c1d1662f212225aa8b92278184dd/H5/Compiler/Translator/Utils/Roslyn/SharpSixRewriter.cs, we've added support for caching the rewritten code, so it only needs to happen once and will re-use it if the file didnt change. I'll also try to add soon the same thing but for the emitter (i.e. cache the generated Javascript)

**Comment by TriEdgeAI** [comment]
Enhancing the transpiler to support the wider C# is not feasible I assume?

**Comment by theolivenbaum** [comment]
That is for sure feasible! Want to do some cleanup first to refactor it to
a more understandable state first, but it should be possible to add the
most needed C# 8.0 features
