### ISSUE TITLE
Local functions No build

### ISSUE THREAD

**Issue by 2505817596** [theolivenbaum/h5#90]
Reproduce the code:

` 
static void Main(string[] args)
 {
     if (true)
     {
         void Test()
         {
         }
         if(true)
         {
             void Test1()
             {
             }
             Test1();
         }
     }
 }
`

results:
` H5.define("FightCore.Program", {
        main: function Main (args) {
            if (true) {
                var Test = null;
                Test = function () { };
                if (true) {
                    [UnknownIdentifierResolveResult Test1]();
                }
            }
        }
    });
`

**Comment by theolivenbaum** [comment]
@2505817596 Think I finally found a fix for this with 16c6677e38076afeb5fe88b6c4decd06a8e42292, let me know if you still see the issue with the new release.
